import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
// import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const router = useRouter();

  if (typeof window !== 'undefined') {
    router.push('/login');
  }

  // if window !== undefined && router.push('/login')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>Admin Menu</main>

      <footer className={styles.footer}>UFACE Admin</footer>
    </div>
  );
};

//getServerSideProps<GetServerSideProps> => user

export default Home;
